version: '3'
volumes:
  redis-data:
    driver: local
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config/config.yml:/app/config/config.yml
      - ./.browser-data:/app/.browser-data
    stdin_open: true
    tty: true
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - redis
      - captcha-resolver
    environment:
      - PORT=${PORT}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CAPTCHA_API_BASE_URL=http://captcha-resolver:1234
      - ACB_MANUAL_LOGIN=${ACB_MANUAL_LOGIN:-false}
      - ACB_SAFEKEY_CONSOLE=${ACB_SAFEKEY_CONSOLE:-false}
  redis:
    image: redis:6.2-alpine
    volumes:
      - redis-data:/data
  captcha-resolver:
    image: registry.gitlab.com/nhayhoc/bank-captcha-server
